# Generated by Django 3.0.7 on 2020-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateField(verbose_name="Date de l'entraînement"),
        ),
        migrations.AlterField(
            model_name='training',
            name='day',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name="Jour de l'entraînement"),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.TimeField(verbose_name="Début de l'entraînement"),
        ),
    ]
