# Generated by Django 3.0.7 on 2020-09-19 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='(catalogue sans nom)', max_length=50, verbose_name='Nom du catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='(produit sans nom)', max_length=50, verbose_name='Article')),
                ('image', models.FileField(blank=True, null=True, upload_to='produits/', verbose_name='Photo')),
                ('size', models.CharField(default='(produit sans taille)', max_length=5, verbose_name='Taille')),
                ('is_available', models.BooleanField(default=True, verbose_name='Produit disponible ?')),
                ('is_free', models.BooleanField(default=False, verbose_name='Produit offert ?')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Prix')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Catalog')),
            ],
        ),
    ]
