# Generated by Django 3.0.7 on 2020-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_different_sizes',
            field=models.BooleanField(default=True),
        ),
    ]
