# Generated by Django 3.0.7 on 2020-09-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_product_has_different_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_different_sizes',
            field=models.BooleanField(default=True, verbose_name='Disponible en différentes tailles ?'),
        ),
    ]
