# Generated by Django 3.0.7 on 2020-09-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20200921_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_different_sizes',
        ),
    ]
