# Generated by Django 3.0.7 on 2020-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_on_board',
        ),
        migrations.AddField(
            model_name='role',
            name='is_in_standby',
            field=models.BooleanField(default=False, verbose_name='Non adhérent(e)'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_member',
            field=models.BooleanField(default=True, verbose_name="Adhérent(e) de l'association"),
        ),
        migrations.AddField(
            model_name='role',
            name='is_president',
            field=models.BooleanField(default=False, verbose_name='Présidence'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_secretary',
            field=models.BooleanField(default=False, verbose_name='Secrétariat'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_treasurer',
            field=models.BooleanField(default=False, verbose_name='Trésorerie'),
        ),
    ]
