# Generated by Django 3.0.7 on 2020-06-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location'),
        ('profiles', '0003_auto_20200609_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
