# Generated by Django 3.0.7 on 2020-06-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200610_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='last_name',
        ),
    ]
