# Generated by Django 3.0.7 on 2020-07-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200622_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personal',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
