# Generated by Django 3.0.7 on 2020-08-05 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200805_0702'),
        ('profiles', '0006_auto_20200729_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone_number',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
