# Generated by Django 3.0.7 on 2020-08-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200805_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='has_private_profile',
            field=models.BooleanField(default=False, verbose_name='Profil privé ?'),
        ),
    ]
