# Generated by Django 3.0.7 on 2020-09-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200909_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='personal',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name="Certificat médical ou licence d'athlétisme"),
        ),
    ]
