# Generated by Django 3.0.7 on 2020-09-14 13:28

from django.db import migrations, models
import teamspirit.profiles.managers


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200909_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id_file',
            field=models.FileField(blank=True, null=True, upload_to=teamspirit.profiles.managers.rename_id_file, verbose_name="Pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='personal',
            name='medical_file',
            field=models.FileField(blank=True, null=True, upload_to=teamspirit.profiles.managers.rename_medical_file, verbose_name='Certificat médical ou licence'),
        ),
    ]
