# Generated by Django 3.0.7 on 2020-10-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201003_0011'),
        ('profiles', '0022_auto_20201003_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
    ]
