# Generated by Django 3.0.7 on 2020-10-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201003_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
    ]
