# Generated by Django 3.0.7 on 2020-10-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20201003_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='phone_number',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
