# Generated by Django 3.0.7 on 2020-09-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0003_auto_20200922_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartline',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
