# Generated by Django 3.0.7 on 2020-09-23 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0005_auto_20200923_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Quantité'),
        ),
    ]
