# Generated by Django 3.0.7 on 2020-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_first', models.CharField(max_length=100)),
                ('label_second', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
