# Generated by Django 3.0.7 on 2020-06-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Libellé du lieu')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
            ],
        ),
    ]
