# Generated by Django 3.0.7 on 2020-10-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201002_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label_first',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Numéro et voie'),
        ),
        migrations.AlterField(
            model_name='address',
            name='label_second',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Complément'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code postal'),
        ),
    ]
