# Generated by Django 3.0.7 on 2020-07-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200729_1940'),
        ('users', '0005_auto_20200619_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
