# Generated by Django 3.0.7 on 2020-09-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200805_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personal',
        ),
    ]
