# Generated by Django 3.0.7 on 2020-09-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200914_1528'),
        ('users', '0008_remove_user_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
            preserve_default=False,
        ),
    ]
