# Generated by Django 3.0.7 on 2020-10-02 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20201002_2332'),
        ('users', '0010_auto_20200925_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
