# Generated by Django 3.0.7 on 2020-10-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201002_2337'),
        ('users', '0011_auto_20201002_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
