# Generated by Django 3.0.7 on 2020-10-02 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20201002_2356'),
        ('users', '0015_auto_20201002_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
