# Generated by Django 3.0.7 on 2020-10-02 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20201002_2359'),
        ('users', '0017_auto_20201002_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=61, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
