# Generated by Django 3.0.7 on 2020-10-02 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20201003_0003'),
        ('users', '0018_auto_20201002_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
