# Generated by Django 3.0.7 on 2020-10-02 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20201003_0023'),
        ('users', '0019_auto_20201003_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
