# Generated by Django 3.0.7 on 2020-10-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20201003_0156'),
        ('users', '0028_auto_20201003_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
