# Generated by Django 3.0.7 on 2020-10-03 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20201003_0212'),
        ('users', '0031_auto_20201003_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
