# Generated by Django 3.0.7 on 2020-10-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20201003_0316'),
        ('users', '0034_auto_20201003_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Personal'),
        ),
    ]
